/*
** syscall.h for syscall in /home/paskal/rendu/System_Unix/PSU_2016_ftrace/include/
**
** Made by Paskal Arzel
** Login   <paskal.arzel@epitech.eu>
**
** Started on  Wed Apr 12 19:29:49 2017 Paskal Arzel
** Last update Wed May  3 22:58:38 2017 Paskal Arzel
*/

#ifndef SYSCALL_H__
#define SYSCALL_H__

#include "ftrace.h"

t_sys g_sys [] =
{{0, "read", "unsigned int", {"int", "void *", "unsigned int", NULL}},
{1, "write", "unsigned int", {"int", "const void *", "unsigned int", NULL}},
{2, "open", "int", {"const char *", "int", "mode_t", NULL}},
{3, "close", "int", {"int", NULL}},
{4, "stat", "int", {"const char *", "struct stat *", NULL}},
{5, "fstat", "int", {"int", "struct stat *", NULL}},
{6, "lstat", "int", {"const char *", "struct stat *", NULL}},
{7, "poll", "int", {"struct pollfd *", "nfds_t", "int", NULL}},
{8, "lseek", "int", {"int", "unsigned int", "int", NULL}},
{9, "mmap", "void *", {"void *", "unsigned int", "int", "int", "int", "unsigned int", NULL}},
{10, "mprotect", "int", {"void *", "unsigned int", "int", NULL}},
{11, "munmap", "int", {"void *", "unsigned int", NULL}},
{12, "brk", "int", {"void *", NULL}},
{13, "rt_sigaction", "int", {"int", "const struct sigaction *", "struct sigaction *", NULL}},
{14, "rt_sigprocmask", "int", {"int", "const sigset_t *", "sigset_t *", NULL}},
{15, "rt_sigreturn", "int", {"...", NULL}},
{16, "ioctl", "int", {"int", "unsigned long", "...", NULL}},
{17, "pread64", "unsigned int", {"int", "void *", "unsigned int", "unsigned int", NULL}},
{18, "pwrite64", "unsigned int", {"int", "const void *", "unsigned int", "unsigned int", NULL}},
{19, "readv", "unsigned int", {"int", "const struct iovec *", "int", NULL}},
{20, "writev", "unsigned int", {"int", "const struct iovec *", "int", NULL}},
{21, "access", "int", {"const char *", "int", NULL}},
{22, "pipe", "int", {"int[2]", NULL}},
{23, "select", "int", {"int", "fd_set *", "fd_set *", "fd_set *", "struct timeval *", NULL}},
{24, "sched_yield", "int", {NULL}},
{25, "mremap", "void *", {"unsigned int", "unsigned int", "int", "...", NULL}},
{26, "msync", "int", {"void *", "unsigned int", "int", NULL}},
{27, "mincore", "int", {"void *", "unsigned int", "unsigned char *", NULL}},
{28, "madvise", "int", {"void *", "unsigned int", "int", NULL}},
{29, "shmget", "int", {"key_t", "unsigned int", "int", NULL}},
{30, "shmat", "void *", {"int", "const void *", "int", NULL}},
{31, "shmctl", "int", {"int", "int", "struct shmid_ds *", NULL}},
{32, "dup", "int", {"int", NULL}},
{33, "dup2", "int", {"int", "int", NULL}},
{34, "pause", "int", {NULL}},
{35, "nanosleep", "int", {"const struct timespec *", "struct timespec *", NULL}},
{36, "getitimer", "int", {"int", "struct itimerval *", NULL}},
{37, "alarm", "unsigned int", {"unsigned int", NULL}},
{38, "setitimer", "int", {"int", "const struct itimerval *", "struct itimerval *", NULL}},
{39, "getpid", "unsigned int", {NULL}},
{40, "sendfile", "unsigned int", {"int", "int", "unsigned int *", "unsigned int", NULL}},
{41, "socket", "int", {"int", "int", "int", NULL}},
{42, "connect", "int", {"int", "const struct sockaddr *", "socklen_t", NULL}},
{43, "accept", "int", {"int", "struct sockaddr *", "socklen_t *", NULL}},
{44, "sendto", "unsigned int", {"int", "const void *", "unsigned int", "int", "const struct sockaddr *", "socklen_t", NULL}},
{45, "recvfrom", "unsigned int", {"int", "void *", "unsigned int", "int", "struct sockaddr *", "socklen_t *", NULL}},
{46, "sendmsg", "unsigned int", {"int", "const struct msghdr *", "int", NULL}},
{47, "recvmsg", "unsigned int", {"int", "struct msghdr *", "int", NULL}},
{48, "shutdown", "int", {"int", "int", NULL}},
{49, "bind", "int", {"int", "const struct sokaddr *", "socklen_t", NULL}},
{50, "listen", "int", {"int", "int", NULL}},
{51, "getsockname", "int", {"int", "struct sockaddr *", "socklen_t *", NULL}},
{52, "getpeername", "int", {"int", "struct sockaddr *", "socklen_t *", NULL}},
{53, "socketpair", "int", {"int", "int", "int", "int *", NULL}},
{54, "setsockopt", "int", {"int", "int", "int", "const void *", "socklen_t", NULL}},
{55, "getsockopt", "int", {"int", "int", "int", "void *", "socklen_t *", NULL}},
{56, "clone", "int", {"int (*fn)(void *)", "void *", "int", "void *", "...", NULL}},
{57, "fork", "unsigned int", {NULL}},
{58, "vfork", "unsigned int", {NULL}},
{59, "execve", "int", {"const char *", "char *const []", "char *const []", NULL}},
{60, "exit", "void", {"int", NULL}},
{61, "wait4", "unsigned int", {"unsigned int", "int *", "int", "struct rusage *", NULL}},
{62, "kill", "int", {"unsigned int", "int", NULL}},
{63, "uname", "int", {"struct utsname *", NULL}},
{64, "semget", "int", {"key_t", "int", "int", NULL}},
{65, "semop", "int", {"int", "struct sembuf *", "unsigned int", NULL}},
{66, "semctl", "int", {"int", "int", "int", "...", NULL}},
{67, "shmdt", "int", {"const void *", NULL}},
{68, "msgget", "int", {"key_t", "int", NULL}},
{69, "msgsnd", "int", {"int", "const void *", "unsigned int", "int", NULL}},
{70, "msgrcv", "unsigned int", {"int", "void *", "unsigned int", "long", "int", NULL}},
{71, "msgctl", "int", {"int", "int", "struct msqid_ds *", NULL}},
{72, "fcntl", "int", {"int", "int", "...", NULL}},
{73, "flock", "int", {"int", "int", NULL}},
{74, "fsync", "int", {"int", NULL}},
{75, "fdatasync", "int", {"int", NULL}},
{76, "truncate", "int", {"const char *", "unsigned int", NULL}},
{77, "ftruncate", "int", {"int", "unsigned int", NULL}},
{78, "getdents", "int", {"unsigned int", "struct linux_dirent *", "unsigned int", NULL}},
{79, "getcwd", "char *", {"char *", "unsigned int", NULL}},
{80, "chdir", "int", {"const char *", NULL}},
{81, "fchdir", "int", {"int", NULL}},
{82, "rename", "int", {"const char *", "const char *", NULL}},
{83, "mkdir", "int", {"const char *", "mode_t", NULL}},
{84, "rmdir", "int", {"const char *", NULL}},
{85, "creat", "int", {"const char *", "mode_t", NULL}},
{86, "link", "int", {"const char *", "const char *", NULL}},
{87, "unlink", "int", {"const char *", NULL}},
{88, "symlink", "int", {"const char *", "const char *", NULL}},
{89, "readlink", "unsigned int", {"const char *", "char *", "unsigned int", NULL}},
{90, "chmod", "int", {"const char *", "mode_t", NULL}},
{91, "fchmod", "int", {"int", "mode_t", NULL}},
{92, "chown", "int", {"const char *", "uid_t", "gid_t", NULL}},
{93, "fchown", "int", {"int", "uid_t", "gid_t", NULL}},
{94, "lchown", "int", {"const char *", "uid_t", "gid_t", NULL}},
{95, "umask", "mode_t", {"mode_t", NULL}},
{96, "gettimeofday", "int", {"struct timeval *", "struct timezone *", NULL}},
{97, "getrlimit", "int", {"int", "struct rlimit *", NULL}},
{98, "getrusage", "int", {"int", "struct rusage *", NULL}},
{99, "sysinfo", "int", {"struct sysinfo *", NULL}},
{100, "times", "clock_t", {"struct tms *", NULL}},
{101, "ptrace", "long", {"long", "unsigned int", "void *", "void *", NULL}},
{102, "getuid", "uid_t", {NULL}},
{103, "syslog", "int", {"int", "char *", "int", NULL}},
{104, "getgid", "gid_t", {NULL}},
{105, "setuid", "int", {"uid_t", NULL}},
{106, "setgid", "int", {"gid_t", NULL}},
{107, "geteuid", "uid_t", {NULL}},
{108, "getegid", "gid_t", {NULL}},
{109, "setpgid", "unsigned int", {"unsigned int", NULL}},
{110, "getppid", "unsigned int", {NULL}},
{111, "getpgrp", "unsigned int", {NULL}},
{112, "setsid", "unsigned int", {NULL}},
{113, "setreuid", "int", {"uid_t", "uid_t", NULL}},
{114, "setregid", "int", {"gid_t", "gid_t", NULL}},
{115, "getgroups", "int", {"int", "gid_t *", NULL}},
{116, "setgroups", "int", {"unsigned int", "const gid_t *", NULL}},
{117, "setresuid", "int", {"uid_t", "uid_t", "uid_t", NULL}},
{118, "getresuid", "int", {"uid_t *", "uid_t *", "uid_t *", NULL}},
{119, "setresgid", "int", {"gid_t", "gid_t", "gid_t", NULL}},
{120, "getresgid", "int", {"gid_t *", "gid_t *", "gid_t *", NULL}},
{121, "getpgid", "unsigned int", {"unsigned int", NULL}},
{122, "setfsuid", "int", {"uid_t", NULL}},
{123, "setfsgid", "int", {"uid_t", NULL}},
{124, "getsid", "unsigned int", {"unsigned int", NULL}},
{125, "capget", "int", {"cap_user_header_t", "cap_user_data_t", NULL}},
{126, "capset", "int", {"cap_user_header_t", "const cap_user_data_t", NULL}},
{127, "rt_sigpending", "int", {"sigset_t *", NULL}},
{128, "rt_sigtimedwait", "int", {"const sigset_t *", "siginfo_t *", "const struct timespec *", NULL}},
{129, "rt_sigqueueinfo", "int", {"unsigned int", "int", "siginfo_t *", NULL}},
{130, "rt_sigsuspend", "int", {"const sigset_t *", NULL}},
{131, "sigaltstack", "int", {"const stack_t *", "stack_t *", NULL}},
{132, "utime", "int", {"const char *", "const struct utimbuf *", NULL}},
{133, "mknod", "int", {"const char *", "mode_t", "unsigned int", NULL}},
{134, "uselib", "int", {"const char *", NULL}},
{135, "personality", "int", {"unsigned long", NULL}},
{136, "ustat", "int", {"unsigned int", "struct ustat *", NULL}},
{137, "statfs", "int", {"const char *", "struct statfs *", NULL}},
{138, "fstatfs", "int", {"int", "struct statfs *", NULL}},
{139, "sysfs", "int", {"int", "const char*", NULL}},
{140, "getpriority", "int", {"int", "id_t", NULL}},
{141, "setpriority", "int", {"int", "id_t", "int", NULL}},
{142, "sched_setparam", "int", {"unsigned int", "const struct sched_param *", NULL}},
{143, "sched_getparam", "int", {"unsigned int", "struct sched_param *", NULL}},
{144, "sched_setscheduler", "int", {"unsigned int", "int", "const struct sched_param *", NULL}},
{145, "sched_getscheduler", "int", {"unsigned int", NULL}},
{146, "sched_get_priority_max", "int", {"int", NULL}},
{147, "sched_get_priority_min", "int", {"int", NULL}},
{148, "sched_rr_get_interval", "int", {"unsigned int", "struct timespec *", NULL}},
{149, "mlock", "int", {"const void *", "unsigned int", NULL}},
{150, "munlock", "int", {"const void *", "unsigned int", NULL}},
{151, "mlockall", "int", {"int", NULL}},
{152, "munlockall", "int", {"int", NULL}},
{153, "vhangup", "int", {NULL}},
{154, "modify_ldt", "int", {"int", "void *", "unsigned long", NULL}},
{155, "pivot_root", "int", {"const char *", "const char *", NULL}},
{156, "_sysctl", "int", {"struct __sysctl_args *", NULL}},
{157, "prctl", "int", {"int", "unsigned long", "unsigned long", "unsigned long", "unsigned long", NULL}},
{158, "arch_prctl", "int", {"", "int", "unsigned long", NULL}},
{159, "adjtimex", "int", {"struct timex *", NULL}},
{160, "setrlimit", "int", {"int", "struct rlimit *", NULL}},
{161, "chroot", "int", {"const char *", NULL}},
{162, "sync", "void", {NULL}},
{163, "acct", "int", {"const char *", NULL}},
{164, "settimeofday", "int", {"const struct timeval *", "const struct timezone *", NULL}},
{165, "mount", "int", {"const char *", "const char *", "const char *", "unsigned long", "const void *", NULL}},
{166, "umount2", "int", {"const char *", "int", NULL}},
{167, "swapon", "int", {"const char *", "int", NULL}},
{168, "swapoff", "int", {"const char *", NULL}},
{169, "reboot", "int", {"int", "int", "int", "void *", NULL}},
{170, "sethostname", "int", {"const char *", "unsigned int", NULL}},
{171, "setdomainname", "int", {"const char *", "unsigned int", NULL}},
{172, "iopl", "int", {"int", NULL}},
{173, "ioperm", "int", {"unsigned long", "unsigned long", "int", NULL}},
{174, "create_module", "caddr_t", {"const char *", "unsigned int", NULL}},
{175, "init_module", "int", {"void *", "unsigned long", "const char *", NULL}},
{176, "delete_module", "int", {"const chat *", "int", NULL}},
{177, "get_kernel_syms", "int", {"struct kernel_sym *", NULL}},
{178, "query_module", "int", {"const char *", "int", "void *", "unsigned int", "unsigned int *", NULL}},
{179, "quotactl", "int", {"int", "const char *", "int", "caddr_t", NULL}},
{180, "nfsservctl", "long", {"int", "struct nfsctl_arg *", "union nfsctl_res *", NULL}},
{181, "getpmsg", "", {NULL}},
{182, "putpmsg", "", {NULL}},
{183, "afs_syscall", "", {NULL}},
{184, "tuxcall", "", {NULL}},
{185, "security", "", {NULL}},
{186, "gettid", "unsigned int", {NULL}},
{187, "readahead", "unsigned int", {"int", "off64_t", "unsigned int", NULL}},
{188, "setxattr", "int", {"const char *", "const char *", "const void *", "unsigned int", "int", NULL}},
{189, "lsetxattr", "int", {"const char *", "const char *", "const void *", "unsigned int", "int", NULL}},
{190, "fsetxattr", "int", {"int", "const char *", "const void *", "unsigned int", "int", NULL}},
{191, "getxattr", "unsigned int", {"const char *", "const char *", "void *", "unsigned int", NULL}},
{192, "lgetxattr", "unsigned int", {"const char *", "const char *", "void *", "unsigned int", NULL}},
{193, "fgetxattr", "unsigned int", {"int", "const char *", "void *", "unsigned int", NULL}},
{194, "listxattr", "unsigned int", {"const char *", "char *", "unsigned int", NULL}},
{195, "llistxattr", "unsigned int", {"const char *", "char *", "unsigned int", NULL}},
{196, "flistxattr", "unsigned int", {"int", "char *", "unsigned int", NULL}},
{197, "removexattr", "int", {"const char *", "const char *", NULL}},
{198, "lremovexattr", "int", {"const char *", "const char *", NULL}},
{199, "fremovexattr", "int", {"int", "const char *", NULL}},
{200, "tkill", "int", {"int", "int", NULL}},
{201, "time", "unsigned int", {"unsigned int *", NULL}},
{202, "futex", "int", {"int *", "int", "int", "const struct timespec *", "int *", "int", NULL}},
{203, "sched_setaffinity", "int", {"unsigned int", "unsigned int", "const cpu_set_t *", NULL}},
{204, "sched_getaffinity", "int", {"unsigned int", "unsigned int", "cpu_setunsigned int *", NULL}},
{205, "set_thread_area", "int", {"struct user_desc *", NULL}},
{206, "io_setup", "int", {"unsigned int", "aio_context_t *", NULL}},
{207, "io_destroy", "int", {"aio_context_t", NULL}},
{208, "io_getevents", "int", {"aio_context_t", "long", "long", "struct io_event *", "struct timespec *", NULL}},
{209, "io_submit", "int", {"aio_context_t", "long", "struct iocb **", NULL}},
{210, "io_cancel", "int", {"aio_context_t", "struct iocb *", "struct io_event *", NULL}},
{211, "get_thread_area", "int", {"struct user_desc *", NULL}},
{212, "lookup_dcookie", "int", {"unsigned int", "char *", "unsigned int", NULL}},
{213, "epoll_create", "int", {"int", NULL}},
{214, "epoll_ctl_old", "int", {"int", NULL}},
{215, "epoll_wait_old", "int", {"int", NULL}},
{216, "remap_file_pages", "int", {"void *", "unsigned int", "int", "unsigned int", "int", NULL}},
{217, "getdents64", "int", {"unsigned int", "struct linux_dirent64 *", "unsigned int", NULL}},
{218, "setunsigned intid_address", "long", {"int *", NULL}},
{219, "restart_syscall", "int", {NULL}},
{220, "semtimedop", "int", {"int", "struct sembuf *", "unsigned int", "const struct timespec *", NULL}},
{221, "fadvise64", "int", {"int", "unsigned int", "unsigned int", "int", NULL}},
{222, "timer_create", "int", {"unsigned int", "struct sigevent *", "timer_t *", NULL}},
{223, "timer_settime", "int", {"timer_t", "int", "const struct itimerspec *", "struct itimerspec *", NULL}},
{224, "timer_gettime", "int", {"timer_t", "struct itimerspec *", NULL}},
{225, "timer_getoverrun", "int", {"timer_t", NULL}},
{226, "timer_delete", "int", {"timer_t", NULL}},
{227, "clock_settime", "int", {"unsigned int", "const struct timespec *", NULL}},
{228, "clock_gettime", "int", {"unsigned int", "struct timespec *", NULL}},
{229, "clock_getres", "int", {"unsigned int", "struct timespec *", NULL}},
{230, "clock_nanosleep", "int", {"unsigned int", "int", "const struct timespec *", "struct timespec *", NULL}},
{231, "exit_group", "void", {"int", NULL}},
{232, "epoll_wait", "int", {"int", "struct epoll_event *", "int", "int", NULL}},
{233, "epoll_ctl", "int", {"int", "int", "int", "struct epoll_event *", NULL}},
{234, "tgkill", "int", {"int", "int", "int", NULL}},
{235, "utimes", "int", {"const char *", "const struct timeval *", NULL}},
{236, "vserver", "void", {NULL}},
{237, "mbind", "long", {"void *", "unsigned long", "int", "const unsigned long *", "unsigned long", "unsigned int", NULL}},
{238, "set_mempolicy", "long", {"int", "const unsigned long *", "unsigned long", NULL}},
{239, "get_mempolicy", "int", {"int *", "unsigned long *", "unsigned long", "unsigned long", "unsigned long", NULL}},
{240, "mq_open", "mqd_t", {"const char *", "int", "mode_t", "struct mq_attr *", NULL}},
{241, "mq_unlink", "int", {"const char *", NULL}},
{242, "mq_timedsend", "int", {"mqd_t", "const char *", "unsigned int", "unsigned int", "const stuct timespec *", NULL}},
{243, "mq_timedreceive", "unsigned int", {"mqd_t", "char *", "unsigned int", "unsigned int *", "const struct timespec *", NULL}},
{244, "mq_notify", "int", {"mqd_t", "const struct sigevent *", NULL}},
{245, "mq_getsetattr", "int", {"mqd_t", "struct mq_attr *", "struct mq_attr *", NULL}},
{246, "kexec_load", "long", {"unsigned long", "unsigned long", "struct kexec_segment *", "unsigned long", NULL}},
{247, "waitid", "int", {"idtype_t", "id_t", "siginfo_t *", "int", NULL}},
{248, "add_key", "key_serial_t", {"const char *", "const char *", "const void *", "unsigned int", "key_serial_t", NULL}},
{249, "request_key", "key_serial_t", {"const char *", "const char *", "const char *", "key_serial_t", NULL}},
{250, "keyctl", "long", {"int", "...", NULL}},
{251, "ioprio_set", "int", {"int", "int", "int", NULL}},
{252, "ioprio_get", "int", {"int", "int", NULL}},
{253, "inotify_init", "int", {NULL}},
{254, "inotify_add_watch", "int", {"int", "const char *", "unsigned int", NULL}},
{255, "inotify_rm_watch", "int", {"int", "int", NULL}},
{256, "migrate_pages", "long", {"int", "unsigned long", "const unsigned long *", "const unsigned long *", NULL}},
{257, "openat", "int", {"int", "const char *", "int", "int", NULL}},
{258, "mkdirat", "int", {"int", "const char *", "int", NULL}},
{259, "mknodat", "int", {"int", "const char *", "int", "int", NULL}},
{260, "fchownat", "int", {"int", "const char *", "uid_t", "gid_t", "int", NULL}},
{261, "futimesat", "int", {"int", "const char *", "const struct timeval *", NULL}},
{262, "newfstatat", "int", {"int", "const char *", "struct stat *", "int", NULL}},
{263, "unlinkat", "int", {"int", "const char *", "int", NULL}},
{264, "renameat", "int", {"int", "const char *", "int", "const char *", NULL}},
{265, "linkat", "int", {"int", "const char *", "int", "const char *", "int", NULL}},
{266, "symlinkat", "int", {"const char *", "int", "const char *", NULL}},
{267, "readlinkat", "unsigned int", {"int", "const char *", "char *", "unsigned int", NULL}},
{268, "fchmodat", "int", {"int", "const char *", "unsigned int", "int", NULL}},
{269, "faccessat", "int", {"int", "const char *", "int", "int", NULL}},
{270, "pselect", "int", {"int", "fd_set *", "fd_set *", "fd_set *", "const struct timespec *", "const sigset_t *", NULL}},
{271, "ppoll", "int", {"struct pollfd *", "unsigned int", "const struct timespec *", "const sigset_t *", NULL}},
{272, "unshare", "int", {"int", NULL}},
{273, "set_robust_list", "long", {"struct robust_list_head *", "unsigned int", NULL}},
{274, "get_robust_list", "long", {"int", "struct robust_list_head **", "unsigned int *", NULL}},
{275, "splice", "unsigned int", {"int", "lunsigned int *", "int", "lunsigned int *", "unsigned int", "unsigned int", NULL}},
{276, "tee", "unsigned int", {"int", "int", "unsigned int", "unsigned int", NULL}},
{277, "sync_file_range", "int", {"int", "unsigned int", "unsigned int", "unsigned int", NULL}},
{278, "vmsplice", "unsigned int", {"int", "const struct iovec *", "unsigned long", "unsigned int", NULL}},
{279, "move_pages", "long", {"int", "unsigned long", "void **", "const int *", "int *", "int", NULL}},
{280, "utimensat", "int", {"int", "const char *", "const struct timespec *", "int", NULL}},
{281, "epoll_pwait", "int", {"int", "struct epoll_event *", "int", "int", "const sigset_t *", NULL}},
{282, "signalfd", "int", {"int", "const sigset_t *", "int", NULL}},
{283, "timerfd_create", "int", {"int", "int", NULL}},
{284, "eventfd", "int", {"unsigned int", "int", NULL}},
{285, "fallocate", "int", {"int", "int", "unsigned int", "unsigned int", NULL}},
{286, "timerfd_settime", "int", {"int", "int", "const struct itimerspec *", "struct itimerspec *", NULL}},
{287, "timerfd_gettime", "int", {"int", "struct itimerspec *", NULL}},
{288, "accept4", "int", {"int", "struct sockaddr *", "int *", "int", NULL}},
{289, "signalfd4", "int", {"int", "const sigsetunsigned int *", "int", NULL}},
{290, "eventfd2", "int", {"unsigned int", "int", NULL}},
{291, "epoll_create1", "int", {"int", NULL}},
{292, "dup3", "int", {"int", "int", "int", NULL}},
{293, "pipe2", "int", {"int *", "int", NULL}},
{294, "inotify_init1", "int", {"int", NULL}},
{295, "preadv", "unsigned int", {"int", "const struct iovec *", "int", "unsigned int", NULL}},
{296, "pwritev", "unsigned int", {"int", "const struct iovec *", "int", "unsigned int", NULL}},
{297, "rt_tgsigqueueinfo", "int", {"unsigned int", "unsigned int", "int", "siginfo_t *", NULL}},
{298, "perf_event_open", "int", {"struct perf_event_attr *", "unsigned int", "int", "int", "unsigned long", NULL}},
{299, "recvmmsg", "unsigned int", {"int", "struct msghdr *", "int", NULL}},
{300, "fanotify_init", "int", {"unsigned int", "unsigned int", NULL}},
{301, "fanotify_mark", "int", {"int", "unsigned int", "unsigned int", "int", "const char *", NULL}},
{302, "prlimit64", "int", {"unsigned int", "int", "const struct rlimit64 *", "struct rlimit64 *", NULL}},
{303, "name_to_handle_at", "int", {"int", "const char *", "struct file_handle *", "int *", "int", NULL}},
{304, "open_by_handle_at", "int", {"int", "struct file_handle *", "int", NULL}},
{305, "clock_adjtime", "int", {"clockid_t", "struct timex *", NULL}},
{306, "syncfs", "int", {"int", NULL}},
{307, "sendmmsg", "unsigned int", {"int", "const struct mmsghdr *", "int", NULL}},
{308, "setns", "int", {"int", "int", NULL}},
{309, "getcpu", "int", {"unsigned *", "unsigned *", "struct getcpu_cache *", NULL}},
{310, "process_vm_readv", "unsigned int", {"unsigned int", "const struct iovec *", "unsigned long", "const struct iovec *", "unsigned long", "unsigned long", NULL}},
{311, "process_vm_writev", "unsigned int", {"unsigned int", "const struct iovec *", "unsigned long", "const struct iovec *", "unsigned long", "unsigned long", NULL}},
{312, "kcmp", "int", {"unsigned int", "unsigned int", "int", "unsigned long", "unsigned long", NULL}},
{313, "finit_module", "int", {"int", "const char *", "int", NULL}},
{314, "sched_setattr", "int", {"unsigned int", "struct sched_attr *", "unsigned int", NULL}},
{315, "sched_getattr", "int", {"unsigned int", "struct sched_attr *", "unsigned int", "unsigned int", NULL}},
{316, "renameat2", "int", {"int", "const char *", "int", "const char *", "unsigned int", NULL}},
{317, "seccomp", "int", {"unsigned int", "unsigned int", "const char *", NULL}},
{318, "getrandom", "int", {"void *", "unsigned int", "unsigned int", NULL}},
{319, "memfd_create", "int", {"const char *", "unsigned int", NULL}},
{320, "kexec_file_load", "long", {"int", "int", "unsigned long", "const char *", "unsigned long", NULL}},
{321, "bpf", "int", {"int", "union bpf_attr *", "unsigned int", NULL}},
{322, "stub_execveat", "int", {"int", "const char *", "const char **", "const char **", "int", NULL}},
{323, "userfaultfd", "int", {"int", NULL}},
{324, "membarrier", "int", {"int", "int", NULL}},
{325, "mlock2", "int", {"const void *", "unsigned int", "int", NULL}},
{326, "copy_file_range", "unsigned int", {"int", "unsigned int *", "int", "unsigned int *", "unsigned int", "unsigned int", NULL}},
{327, "preadv2", "unsigned int", {"int", "const struct iovec *", "int", "int", "int", "int", NULL}},
{328, "pwritev2", "unsigned long", {"const struct iovec *", "int", "int", "int", "int", NULL}},
{-1, NULL, NULL, {NULL}}
};

#endif
